[package]
name = "rust-belt"
version = "1.0.0"
authors = [
    "johnthagen <johnthagen@gmail.com>",
    "theandrewdavis <theandrewdavis@gmail.com>",
    "mcdenhoed <mcdenhoed@gmail.com>",
]

[dependencies]
piston_window = "0.66.0"
piston-music = "0.21.0"
rand = "0.3.15"